local api = require("gemini.api")

describe("gemini_api", function()
  it("should greet", function()
    local response = api.gemini_generate_content('Hello there', api.MODELS.GEMINI_1_0_PRO)
    print(response)
    assert(#response > 0)
  end)

  it("should write some code", function()
    local response = api.gemini_generate_content('Write a hello world program in c++', api.MODELS.GEMINI_1_0_PRO)
    print(response)
    assert(#response > 0)
  end)
end)
